API_URL=@apiUrl@
API_KEY=__API_KEY__
MODE=stream
UPDATE_FREQUENCY=10
REQUEST_TIMEOUT=1000
BOUNCING_ON_TYPE=ban
FALLBACK_REMEDIATION=ban
EXCLUDE_LOCATION=/.well-known/acme-challenge
BAN_TEMPLATE_PATH=@banTemplate@
APPSEC_URL=@appsecUrl@
APPSEC_FAILURE_ACTION=passthrough
APPSEC_CONNECT_TIMEOUT=200
APPSEC_SEND_TIMEOUT=200
APPSEC_PROCESS_TIMEOUT=1000
ALWAYS_SEND_TO_APPSEC=false
APPSEC_DROP_UNREADABLE_BODY=false
SSL_VERIFY=false
