access_log @crowdsecLog@ combined;

lua_package_path "@luaPath@;;";
lua_package_cpath "@luaCPath@;;";
lua_shared_dict crowdsec_cache 50m;
lua_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;

init_by_lua_file @initLua@;
init_worker_by_lua_file @workerLua@;
access_by_lua_file @accessLua@;
