access_log @crowdsecLog@ combined;

lua_shared_dict crowdsec_cache 50m;
# lua_ssl_trusted_certificate comes from services.nginx.lua.enable

init_by_lua_file @initLua@;
init_worker_by_lua_file @workerLua@;
access_by_lua_file @accessLua@;
